In [8]:
#поиск машинного нуля
n=100
p=2.0**(-n)
while p!=0:
    n=n+1
    p=2.0**(-n)
print(n-1, f": {2.0**(-n+1)}")
print(n,": ",p)


1075 : 5e-324
1076 :  0.0


вывод: у данного эвм порог машинного нуля составляет 2^(-1075)

In [9]:
#поиск относительной погрешности
n=10
eps=2.0**(-n)
while 1+eps>1:
    n+=1
    eps/=2
n-=1
eps*=2
print(n,": ",eps)

52 :  2.220446049250313e-16


вывод: относительная погрешность данного эвм составляет 2^(-52)

In [10]:
#поиск машинной бесконечности
n=100
p=2.0**(n)
try: 
 while True:
    n+=1
    p=2.0**(n)
except OverflowError:
    print("вычисление ещё возможно")
    print(n-1,f": {2.0**(n-1)}")
    print("вычисление уже невозможно")
    print(n,": ошибка")

вычисление ещё возможно
1023 : 8.98846567431158e+307
вычисление уже невозможно
1024 : ошибка


вывод: у данного эвм порог машинной бесконечности составляет 2^1023

In [11]:
import math
def f(t):
  return x*x
def y(x):
  return math.sqrt(x)
x=4.0
print(x,f": {f(x)},{y(x)}")

4.0 : 16.0,2.0


In [19]:
import math
def F(x):
  return x*x
def f(x,n):
    s=x
    for i in range(n+1):
     s=F(s)
    return s
x=4.0;
n=5
print(n+1,f": {f(x,n)}")

6 : 3.402823669209385e+38


Задача 1.
Осуществить рекурсивное вычисление значения заданной функции f(x) и возврат к исходному 
значению x, используя рекурсивное вычисление обратной функции. Вычислить разность 
полученного значения и исходной величины x. Определить количество верных цифр в 
значении, полученном рекурсивным вычислением обратной функции.

In [4]:
#мой вариант(15)
#1 задание
import math
def F(x):
  return (3*x)**(1.0/3.0)
def G(x):
    return x**(3)/3.0
def f(x,n):
    s=x
    for i in range(n+1):
     s=F(s)
    return s
def g(x,n):
    s=x
    for i in range(n+1):
     s=G(s)
    return s
def col(x,delt):
    s=x
    k=0
    while s>=1:
        s/=10
        k+=1
    s=10**(k-1)
    k=0
    while s>delt:
      s/=10
      k+=1
    return k
        
x=0.7;
n=25
#s1 - это вычесленное в цикле по i от 0 до N следующее значение величины s как значение функции
#от предыдущего значения
s1=f(x,n);
#s2– это полученное в следствии рекурсии от s1 приближенное значение, а delt – его погрешность
s2=g(s1,n);
delt=abs(x-s2)
print("s1: ",s1)
print("s2: ",s2)
print("delt: ",delt)
print("количество верных цифр у результата равно",f"{col(s2,delt)}")

s1:  1.73205080756826
s2:  0.6999727878809431
delt:  2.721211905687415e-05
количество верных цифр у результата равно 4


Задача 2.
Используя алгоритм выполнения Задачи 1, для каждого значения глубины рекурсии N от 10 до 
80 определить количество верных цифр в полученном приближенном значении исходной 
величины. Объяснить полученные результаты.


Вывод: чем больше мы берем глубину рекурсии, тем меньше становится точность получаемого результата. Например, начиная с глубины n=40 количество верных знаков становится равным 0, значение s1 и delt перестает меняться.

In [32]:
#2 задание
import math
def F(x):
  return (3*x)**(1.0/3.0)
def G(x):
    return x**(3)/3.0
def f(x,n):
    s=x
    for i in range(n+1):
     s=F(s)
    return s
def g(x,n):
    s=x
    for i in range(n+1):
     s=G(s)
    return s 
def col(x,delt):
    s=x
    k=0
    while s>=1:
        s/=10
        k+=1
    if(k>0):
     s=10**(k-1)
    else:
     i=0;
     s=x;
     if(s!=0):
       while s<1:
        s*=10
        i=1+i
       s=10**(-i)
     else:
        k=0;
        return k
    k=0
    while s>delt:  
       s/=10
       k+=1
    return k
def auto(x):
    for t in range(10,100,10):
        s1=f(x,t);
        s2=g(s1,t);
        delt=abs(x-s2)
        print(t," ",s2," ",delt," ",f"{col(s2,delt)}")
    return
x=0.7
print("x=",x)
print("N / s2 / delt / кол-во верных цифр")
auto(x)

x= 0.7
N / s2 / delt / кол-во верных цифр
10   0.6999999999983727   1.627253887193092e-12   11
20   0.7000003224332624   3.224332624229831e-07   6
30   0.6967615199937839   0.0032384800062160712   2
40   0.0   0.7   0
50   0.0   0.7   0
60   0.0   0.7   0
70   0.0   0.7   0
80   0.0   0.7   0
90   0.0   0.7   0
